# Generated by Django 5.1.1 on 2024-12-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
