# Generated by Django 5.1.1 on 2024-12-21 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0017_projectactivity_delete_usersettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
