# Generated by Django 5.1.4 on 2025-06-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0021_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('important and urgent', 'Important and Urgent'), ('important but not urgent', 'Important but not Urgent'), ('not important but urgent', 'Not important but Urgent'), ('not important and not urgent', 'Not important and not Urgent')], max_length=50),
        ),
    ]
