# Generated by Django 5.1.1 on 2024-10-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
