# Generated by Django 5.1.1 on 2024-10-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_newpost_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpost',
            name='liked',
        ),
        migrations.AlterField(
            model_name='newpost',
            name='text',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
