# Generated by Django 5.1.1 on 2024-12-09 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_remove_group_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='group',
            name='author',
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.RemoveField(
            model_name='group',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
