# Generated by Django 5.1.1 on 2024-12-21 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0018_delete_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouptask',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='grouptask',
            name='project',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='projectactivity',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectactivity',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='GroupTask',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectActivity',
        ),
    ]
