# Generated by Django 5.1.4 on 2025-03-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0019_remove_grouptask_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/profie_image.png', null=True, upload_to='images/'),
        ),
    ]
