# Generated by Django 5.1.4 on 2025-03-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0020_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/profile_image.png', null=True, upload_to='images/'),
        ),
    ]
