# Generated by Django 5.0.7 on 2024-08-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_bid_id_alter_comment_id_alter_listing_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=185, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='listing',
            field=models.ManyToManyField(blank=True, related_name='comment', to='auctions.listing'),
        ),
    ]
