# Generated by Django 5.0.7 on 2024-08-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_comment_listing_comment_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=49, null=True),
        ),
    ]
