# Generated by Django 5.0.7 on 2024-08-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_bid_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
