# Generated by Django 5.0.7 on 2024-08-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_listing_url_alter_bid_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='url',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
