# Generated by Django 5.0.7 on 2024-08-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_remove_watchlist_listing_watchlist_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
