# Generated by Django 5.0.7 on 2024-08-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=3003, null=True),
        ),
    ]
